
jobs:
- job: Repometrics
  pool:
    vmImage: 'ubuntu-16.04'

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      cp tools/repo_metrics/config_template.py tools/repo_metrics/config.py
      sed -i ''s/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/$(github_token)/g'' tools/repo_metrics/config.py
      sed -i ''s/XXXXXXXXXXXXXXXXXXXXXXXXX/$(cosmosdb_connectionstring)/g'' tools/repo_metrics/config.py
      echo $(github_token)
      echo $(cosmosdb_connectionstring)
    displayName: Configure CosmosDB Connection

  - script: | 
      python -m pip install python-dateutil>=2.80 pymongo>=3.8.0 gitpython>2.1.11 requests>=2.21.0
      python tools/repo_metrics/track_metrics.py --github_repo "https://github.com/microsoft/ComputerVision" --save_to_database
    displayName: Python script to record stats


